Create the ListJob in the main thread (in KioFuseApp) because KIO can't handle non-main threads accessing it.
I'm encountering a weird compilation error: When compiling kiofuseapp.h, gcc says ListJobHelper is undeclared, even though this class should definitely be known because of #include "jobhelpers.h". Strangely enough, changing ListJobHelper to its parent, BaseJobHelper, works. Even more strangely, I can cast it to ListJobHelper inside listJobMainThread(). If anyone has any insight into why ListJobHelper is known to kiofuseapp.cpp but not known to kiofuseapp.h, please let me know.